---
# tasks file for user

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version >= '7' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version >= "7" )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version == "31" )
        ) or
        ( ansible_distribution == "Debian" and ( ansible_distribution_major_version == "10" )
        ) or
        ( ansible_distribution == "Ubuntu" and ( ansible_distribution_major_version == "18" )
        )

- name: sudo is installed
  package:
    name: sudo
    state: present
  become: true

- name: groups are created
  group:
    name: "{{ item }}"
  become: true
  loop: "{{ users_groups }}"

- include_tasks: user.yml
  loop: "{{ users_username }}"
